### ISSUE TITLE
Failure to add secondary IP to a NIC for a VM in a project

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack-terraform-provider#31] opened 2022-01-31 08:01 UTC
##### ISSUE TYPE

 * Bug Report
 
 ##### COMPONENT NAME
~~~
Network -  secondary IP 
~~~

##### CONFIGURATION
```
#-------------------CloudStack Provider initiation---------------------------------------------#

terraform {
  required_providers {
    cloudstack = {
      source = "cloudstack/cloudstack"
      version = "0.4.0-RC1"
    }
  }
}

#-------------------CloudStack environment variables---------------------------------------------#

variable "cloudstack_api_url" {
  type = string
  default = "http://10.0.35.183:8080/client/api"
}

variable "cloudstack_api_key" {
  type = string
  default = "xxxx"
}

variable "cloudstack_secret_key" {
  type = string
  default = "yyyy"
}

#-------------------CloudStack zone details---------------------------------------------#

variable "zoneId" {
  type = string
  default = "xxxx"
}

#-------------------CloudStack template details---------------------------------------------#

variable "templateId" {
  type = string
  default = "xxxx"
}

#-------------------CloudStack service offering details---------------------------------------------#

variable "serviceOfferingId" {
  type = string
  default = "xxxx"
}

#-------------------Terraform and CloudStack linking---------------------------------------------#

provider "cloudstack" {
  # Configuration options
  api_url    = "${var.cloudstack_api_url}"
  api_key    = "${var.cloudstack_api_key}"
  secret_key = "${var.cloudstack_secret_key}"
}

#-------------------Creating an isolated network---------------------------------------------#

resource "cloudstack_network" "N1user" {
  name             = "Network1user"
  cidr             = "10.200.0.0/24"
  network_offering = "DefaultIsolatedNetworkOfferingWithSourceNatService"
  zone             = "${var.zoneId}"
  project          = "myProject"
}

#-------------------Creating SSH Key Pair ---------------------------------------------#

resource "cloudstack_ssh_keypair" "myKeyNew" {
  name       = "myKeyNew"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
  project    = "myProject"
}


#-------------------Creating Virtual Machine in Project ---------------------------------------------#

resource "cloudstack_instance" "webuser" {
  name             = "VM1TestUser-test1"
  display_name = "VM1Test-User"
  service_offering = "${var.serviceOfferingId}"
  network_id       = cloudstack_network.N1user.id
  template         = "${var.templateId}"
  zone             = "${var.zoneId}"
  keypair          = cloudstack_ssh_keypair.myKeyNew.name
  project          = "myProject"
  expunge          = "true"
}

#------------------- Add secondary IP address -------------------------------------------#
resource "cloudstack_secondary_ipaddress" "default" {
  virtual_machine_id = cloudstack_instance.webuser.id
}
```

##### EXPECTED RESULTS
~~~
Successfully adds secondary IP to the NIC
~~~

##### ACTUAL RESULTS

~~~
Fails to add secondary IP
~~~

Relevant logs:
```
$ terraform apply 
cloudstack_ssh_keypair.myKeyNew: Refreshing state... [id=myKeyNew]
cloudstack_network.N1: Refreshing state... [id=011244ed-3514-47b0-9d68-3c62a1c27a16]
cloudstack_network.N1user: Refreshing state... [id=11d931ad-753d-48d8-9f58-7b7d5d080906]
cloudstack_instance.VM1: Refreshing state... [id=2c13fb87-0438-434e-8378-91e6b8efb377]
cloudstack_instance.webuser: Refreshing state... [id=cff07d71-ed1d-48e8-a19f-65ac46d2e60c]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudstack_secondary_ipaddress.default will be created
  + resource "cloudstack_secondary_ipaddress" "default" {
      + id                 = (known after apply)
      + ip_address         = (known after apply)
      + nic_id             = (known after apply)
      + virtual_machine_id = "cff07d71-ed1d-48e8-a19f-65ac46d2e60c"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudstack_secondary_ipaddress.default: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudstack_secondary_ipaddress.default, provider "provider[\"registry.terraform.io/cloudstack/cloudstack\"]" produced an unexpected new value: Root resource was present, but
│ now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Corresponding terraform logs:

```
2022-01-31T13:02:41.130+0530 [INFO]  provider.terraform-provider-cloudstack_v0.4.0-RC1: configuring server automatic mTLS: timestamp=2022-01-31T13:02:41.129+0530
2022-01-31T13:02:41.142+0530 [DEBUG] provider: using plugin: version=5
2022-01-31T13:02:41.142+0530 [DEBUG] provider.terraform-provider-cloudstack_v0.4.0-RC1: plugin address: address=/tmp/plugin2527697329 network=unix timestamp=2022-01-31T13:02:41.142+0530
2022-01-31T13:02:41.175+0530 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2022-01-31T13:02:41.177+0530 [DEBUG] No provider meta schema returned
2022-01-31T13:02:41.179+0530 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/cloudstack/cloudstack\"]" changed the config value, but that value is unused
2022-01-31T13:02:41.180+0530 [INFO]  Starting apply for cloudstack_secondary_ipaddress.default
2022-01-31T13:02:41.180+0530 [DEBUG] cloudstack_secondary_ipaddress.default: applying the planned Create change
2022-01-31T13:02:41.711+0530 [DEBUG] provider.terraform-provider-cloudstack_v0.4.0-RC1: 2022/01/31 13:02:41 [DEBUG] Virtual Machine cff07d71-ed1d-48e8-a19f-65ac46d2e60c does no longer exist
2022-01-31T13:02:41.719+0530 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudstack/cloudstack/0.4.0-RC1/linux_amd64/terraform-provider-cloudstack_v0.4.0-RC1 pid=3455285
2022-01-31T13:02:41.719+0530 [DEBUG] provider: plugin exited

```

Logs indicate that it is not able to find the VM:

**2022-01-31T13:02:41.711+0530 [DEBUG] provider.terraform-provider-cloudstack_v0.4.0-RC1: 2022/01/31 13:02:41 [DEBUG] Virtual Machine cff07d71-ed1d-48e8-a19f-65ac46d2e60c does no longer exist**

We need the resource cloudstack_secondary_ipaddress to take project_id as an input.

**Comment by DaanHoogland** [comment] 2022-01-31 11:05
@Pearl1594 is this a cloudstack issue? I.E. does the API allow the action that the tf provider can't?

**Comment by Pearl1594** [comment] 2022-01-31 11:11
I was able to do it directly on ACS, so I believe it's a limitation on the provider end - only when the scope is within a project. The issue I believe is that we do not have support for providing project as an input.

**Comment by DaanHoogland** [comment] 2022-02-01 14:03
I have run your config changing only the keys and ids at the top. I needed to munaually create the project called 'myProject' but then the environment deployed without errors. I checked if the network existed in the project and if the VM had a secondary ip. all good. also destroying went without error messages.

**Comment by DaanHoogland** [comment] 2022-02-01 14:04
not sure what your issue was but something else must have been in play, @Pearl1594 . Note however that I executed it in a simulated environment.

**Comment by onitake** [comment] 2022-02-02 16:53
@Pearl1594 It sounds to me like this is a problem with your cloudstack_secondary_ipaddress.default resource. It lacks all the parameters the other resources have (such as zone and project_id).

@DaanHoogland I wonder why it worked for you. Perhaps you're using a global admin that can see all VMs in all projects?

On the other hand, I think these are parameters that should not be specified on individual resources, but on the provider. It doesn't really make sense to write them over and over again. If you need to access multiple projects or zones, you can use multiple providers in the same Terraform script.

Here's an example on how this is done when you need to access multiple AWS regions: https://www.terraform.io/language/providers/configuration#selecting-alternate-provider-configurations
Perhaps the CloudStack Terraform provider should adopt a similar approach?

(Disclaimer: I haven't used the ACS Terraform provider myself, but I have quite a bit of experience with Terraform in general)

**Comment by DaanHoogland** [comment] 2022-02-02 17:10
> @DaanHoogland I wonder why it worked for you. Perhaps you're using a global admin that can see all VMs in all projects?

Yes, i did.

**Comment by kiranchavala** [comment] 2024-03-05 14:46
@Pearl1594 

Not able to reproduce the issue, I was able to deploy a vm and add secondary IP to a NIC for a VM in a project.

Let me know if can close the issue 

My sample terraform file 


```
provider "cloudstack" {
  api_url    = var.cloudstack_api_url
  api_key    = var.cloudstack_api_key
  secret_key = var.cloudstack_secret_key

}


resource "cloudstack_network" "test-network" {
  name             = var.network_name
  cidr             = "10.0.0.0/24"
  network_offering = var.network_offering
  zone             = var.zone
  project = "test"
  
}



resource "cloudstack_instance" "test-vm" {
  name             = var.instance_name
  service_offering = var.instance_service_offering
  network_id       = cloudstack_network.test-network.id
  template         = var.instance_template
  zone             = var.zone
  project = "test"
  
  expunge = true
  depends_on = [
   cloudstack_network.test-network
 ]
  
}




resource "cloudstack_secondary_ipaddress" "default" {
  virtual_machine_id = cloudstack_instance.test-vm.id
  
  depends_on = [ cloudstack_network.test-network, cloudstack_instance.test-vm ]



}

```

**Comment by kiranchavala** [comment] 2024-03-07 10:12
Closing the issue as the issue is not reproducible on the latest build

**Closed by kiranchavala** 2024-03-07 10:12 UTC
