### ISSUE TITLE
network_id remains empty after creating IP address resource

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack-terraform-provider#32] opened 2022-03-29 20:11 UTC
Greetings everyone.

I ran into an issue where the assigned network_id doesn't get saved in the terraform.tfstate file. As a result, subsequent terraform applies will destroy/recreate the IP addresses because it thinks the network_id has changed.

Edit: I'm using the latest version of this provider built against cloudstack-go v2.12. Terraform version 1.1.7. CloudStack version 4.16.1.

Here is how I create an IP address:
```
resource "cloudstack_ipaddress" "public_ip" { 
    count = "${var.num_vms_to_create}" 
 
    vpc_id = "${cloudstack_vpc.default.id}" 
    network_id = "${cloudstack_network.mynet.id}" 
} 
```

When applying this on multiple runs, Terraform will show the following (note that network_id is being added even though the resource is created properly in CloudStack):
```
Terraform will perform the following actions:

  # cloudstack_ipaddress.public_ip[2] must be replaced
-/+ resource "cloudstack_ipaddress" "public_ip" {
      ~ id            = "c823415a-32d4-4fe1-ac7d-65e5c38b5a6b" -> (known after apply)
      ~ ip_address    = "10.44.121.58" -> (known after apply)
      ~ is_source_nat = false -> (known after apply)
      + network_id    = "0aa28065-2d46-4367-a7c0-0e065218aea5" # forces replacement
      + project       = (known after apply)
      ~ tags          = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

The terraform.tfstate file lists the IP address with an empty network_id string.
```
    {   
      "mode": "managed", 
      "type": "cloudstack_ipaddress", 
      "name": "public_ip", 
      "provider": "provider[\"registry.terraform.io/cloudstack/cloudstack\"]", 
      "instances": [ 
        {   
          "index_key": 0,  
          "schema_version": 0,  
          "attributes": { 
            "id": "2bdbc636-f6cd-47cc-b462-ae76351b993e", 
            "ip_address": "10.44.120.53", 
            "is_portable": false, 
            "is_source_nat": false, 
            "network_id": "",            <----- shouldn't be empty
            "project": "", 
            "tags": {}, 
            "vpc_id": "5df887ba-9085-4d4b-a613-e6a7ba2e5ad4", 
            "zone": null 
          },  
          "sensitive_attributes": [], 
          "dependencies": [ 
            "cloudstack_network.mynet", 
            "cloudstack_network_acl.default", 
            "cloudstack_vpc.default" 
          ] 
        },  
```

# Workaround
I was able to 'fix' this issue by removing the conditional [`d.GetOk("network_id")`](https://github.com/apache/cloudstack-terraform-provider/blob/main/cloudstack/resource_cloudstack_ipaddress.go#L167) and always setting `network_id` based on the `Associatednetworkid` value from the CloudStack-go library. I'm not sure why that condition would be failing though.

Any advice? Thanks!

**Comment by Damans227** [comment] 2022-04-12 14:13
Hi @Pearl1594 @kohrar This seems like an interesting issue, and I will start looking into it today. I am going to try reproducing it locally and will keep you folks posted with the progress.

**Comment by synergiator** [comment] 2022-04-13 03:39
@Damans227 side note - please link to the instructions you used to install the simulator?

**Comment by Damans227** [comment] 2022-04-13 03:47
> @Damans227 side note - please link to the instructions you used to install the simulator?

I used mbx: 

https://github.com/shapeblue/mbx

**Comment by synergiator** [comment] 2022-04-13 03:52
@Damans227 thx

**Comment by Damans227** [comment] 2022-04-16 19:17
I think I can reproduce the issue. Following is the `terraform configuration` and the `terraform.tfstate` respectively, for a public ip address being created: 

```
resource "cloudstack_ipaddress" "public_ip" { 
 
    vpc_id = "ce9042a1-c818-4a93-803e-f86b5d38048e" 
    network_id = "b9c953a0-8686-4240-b8a4-43849f7079ff" 
} 
```


```
{
  "version": 4,
  "terraform_version": "1.1.7",
  "serial": 1,
  "lineage": "03e88dc2-ac88-c672-421f-26098d9ba754",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "cloudstack_ipaddress",
      "name": "public_ip",
      "provider": "provider[\"registry.terraform.io/cloudstack/cloudstack\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "f245d0d3-46e3-4549-9ad9-dc1b0379c181",
            "ip_address": "172.20.1.66",
            "is_portable": false,
            "is_source_nat": false,
            "network_id": "", <-------------------------- network id is empty 
            "project": "",
            "tags": {},
            "vpc_id": "ce9042a1-c818-4a93-803e-f86b5d38048e",
            "zone": null
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}

```

**Comment by Damans227** [comment] 2022-04-23 16:49
@kohrar So, in your workaround, how are you always setting `network_id` based on the `Associatednetworkid`? 

I tested this issue further, i.e., removed the conditional to set the `network_id` as follows and created a new provider binary: 

```
d.Set("network_id", ip.Associatednetworkid)
```
Yet, the `network_id` remained empty in the `terraform.tfstate` for me. 

Interestingly, when I use the combination of `zone` and `network_id` in `main.tf`, the `network_id` alwyas gets stored in the `terraform.tfstate` successfully. 

```
resource "cloudstack_ipaddress" "public_ip" { 
    zone = "DC"
    network_id = "b9c953a0-8686-4240-b8a4-43849f7079ff" 
} 
```

**Comment by kohrar** [comment] 2022-04-25 00:59
Hi @Damans227 -- Thanks for looking into this issue.

> removed the conditional ...
> `d.Set("network_id", ip.Associatednetworkid)`

Yup, that's exactly what I did. 

Would the network resource I specify make a difference? This is what I do and that also includes the zone and VPC.

```
# Create a new VPC 
resource "cloudstack_vpc" "default" { 
  name = "leo-vpc" 
  display_text = "leo-vpc" 
  cidr = "192.168.0.0/16" 
  vpc_offering = "Default VPC offering" 
  zone = "zone1" 
} 
 
# Create a new network in the VPC 
resource "cloudstack_network" "leosnet" { 
    name = "leo-net" 
    display_text = "leo-net" 
    cidr = "192.168.1.0/24" 
    network_offering = "UnrestrictedIsolatedNetworkOfferingForVpcNetworks" 
    acl_id = "${cloudstack_network_acl.default.id}" 
    vpc_id = "${cloudstack_vpc.default.id}" 
    zone = "zone1" 
} 

# Create a new public IP address for this network 
resource "cloudstack_ipaddress" "public_ip" { 
    count = "1" 
 
    vpc_id = "${cloudstack_vpc.default.id}" 
    network_id = "${cloudstack_network.leosnet.id}" 
} 
```

Are you also using the latest version of cloudstack-go when compiling the terraform provider? At the time of my original testing, I had to use https://github.com/tetra12/cloudstack-go as a replacement since the API changed in 4.16 broke a few things. I noticed that the PR was merged last week and I can re-test in the next few days with the latest version of cloudstack-go and see if the behavior remains the same.

**Comment by Damans227** [comment] 2022-04-29 00:16
Hi @kohrar 
> 
> Would the network resource I specify make a difference? This is what I do and that also includes the zone and VPC.
> 

Umm, can you try adding `zone1` in the `cloudstack_ipaddress` resource and then try again? Basically, like this:

```
resource "cloudstack_ipaddress" "public_ip" { 
    count = "1" 
 
    vpc_id = "${cloudstack_vpc.default.id}" 
    network_id = "${cloudstack_network.leosnet.id}" 
    zone = "zone1" 
} 

``` 

> 
> Are you also using the latest version of cloudstack-go when compiling the terraform provider? 

So, I didn't change the default version of  `cloudstack-go` imported in the `resource_cloudstack_ipaddress.go` file. If I follow the location of the `cloudstack-go` import, it takes me to [v2.11.0.](https://pkg.go.dev/github.com/apache/cloudstack-go/v2@v2.11.0/cloudstack).

**Comment by kohrar** [comment] 2022-04-29 23:06
Hi @Damans227 

I switched back to the default terraform CloudStack provider (v0.4.0) and tried to specify a zone to the IP address resource with the same result. This is what I have:
<details>
<summary>main.tf</summary>

```
# Configure the CloudStack Provider
terraform {
  required_providers {
    cloudstack = {
      source = "cloudstack/cloudstack"
      version = "0.4.0"
    }
  }
}

provider "cloudstack" {
  api_url    = "${var.cloudstack_api_url}"
  api_key    = "${var.cloudstack_api_key}"
  secret_key = "${var.cloudstack_secret_key}"
}



# Create a new VPC
resource "cloudstack_vpc" "default" {
  name = "test-vpc"
  display_text = "test-vpc"
  cidr = "192.168.0.0/16"
  vpc_offering = "Default VPC offering"
  zone = "zone1"
}

# Create a new ACL
resource "cloudstack_network_acl" "default" {
    name  = "test-vpc-acl"
    vpc_id = "${cloudstack_vpc.default.id}"
}

# One ingress and one egress rule for the ACL
resource "cloudstack_network_acl_rule" "ingress" {
    acl_id = "${cloudstack_network_acl.default.id}"

    rule {
        action       = "allow"
        cidr_list    = ["10.0.0.0/8"]
        protocol     = "tcp"
        ports        = ["22"]
        traffic_type = "ingress"
    }

    rule {
        action       = "allow"
        cidr_list    = ["0.0.0.0/0"]
        protocol     = "tcp"
        ports        = ["80", "443"]
        traffic_type = "ingress"
    }
}

resource "cloudstack_network_acl_rule" "egress" {
    acl_id = "${cloudstack_network_acl.default.id}"

    rule {
        action       = "allow"
        cidr_list    = ["0.0.0.0/0"]
        protocol     = "all"
        traffic_type = "egress"
    }
}


# Create a new network in the VPC
resource "cloudstack_network" "testnet" {
    name = "test-net"
    display_text = "test-net"
    cidr = "192.168.1.0/24"
    network_offering = "UnrestrictedIsolatedNetworkOfferingForVpcNetworks"
    acl_id = "${cloudstack_network_acl.default.id}"
    vpc_id = "${cloudstack_vpc.default.id}"
    zone = "zone1"
}


# Create a new public IP address for this network
resource "cloudstack_ipaddress" "public_ip" {
    vpc_id = "${cloudstack_vpc.default.id}"
    network_id = "${cloudstack_network.testnet.id}"

    zone = "zone1"
}

# Create a port forwarding for SSH to the first VM we create
resource "cloudstack_port_forward" "ssh" {
    ip_address_id = "${cloudstack_ipaddress.public_ip.id}"

    forward {
        protocol  = "tcp"
        private_port = 22
        public_port = 22

        virtual_machine_id = "${cloudstack_instance.testvm.id}"
    }
}

# Create VMs. We can create multiples by specifying count=
resource "cloudstack_instance" "testvm" {
  name = "test-rocky1"
  zone = "zone1"
  service_offering = "rcs.c1"

  # This template was created by Packer with CloudInit support
  template = "RockyLinux 8.5, generated on 2022-04-19T17:00:43Z"
  network_id = "${cloudstack_network.testnet.id}"

  expunge = true

  user_data = <<EOF
#cloud-config

ssh_pwauth: yes
disable_root: false
chpasswd:
  list: |
    root:password
  expire: false

EOF
}

```
</details>


<details>
<summary>terraform apply output</summary>

```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudstack_instance.testvm will be created
  + resource "cloudstack_instance" "testvm" {
      + display_name     = (known after apply)
      + expunge          = true
      + group            = (known after apply)
      + id               = (known after apply)
      + ip_address       = (known after apply)
      + name             = "test-rocky1"
      + network_id       = (known after apply)
      + project          = (known after apply)
      + root_disk_size   = (known after apply)
      + service_offering = "rcs.c1"
      + start_vm         = true
      + tags             = (known after apply)
      + template         = "RockyLinux 8.5, generated on 2022-04-19T17:00:43Z"
      + user_data        = "f96d6fc6c87d153271bed7f13c557e517c137458"
      + zone             = "zone1"
    }

  # cloudstack_ipaddress.public_ip will be created
  + resource "cloudstack_ipaddress" "public_ip" {
      + id            = (known after apply)
      + ip_address    = (known after apply)
      + is_portable   = false
      + is_source_nat = (known after apply)
      + network_id    = (known after apply)
      + project       = (known after apply)
      + tags          = (known after apply)
      + vpc_id        = (known after apply)
      + zone          = "zone1"
    }

  # cloudstack_network.testnet will be created
  + resource "cloudstack_network" "testnet" {
      + acl_id           = (known after apply)
      + cidr             = "192.168.1.0/24"
      + display_text     = "test-net"
      + endip            = (known after apply)
      + gateway          = (known after apply)
      + id               = (known after apply)
      + name             = "test-net"
      + network_domain   = (known after apply)
      + network_offering = "UnrestrictedIsolatedNetworkOfferingForVpcNetworks"
      + project          = (known after apply)
      + source_nat_ip_id = (known after apply)
      + startip          = (known after apply)
      + tags             = (known after apply)
      + vpc_id           = (known after apply)
      + zone             = "zone1"
    }

  # cloudstack_network_acl.default will be created
  + resource "cloudstack_network_acl" "default" {
      + description = (known after apply)
      + id          = (known after apply)
      + name        = "test-vpc-acl"
      + vpc_id      = (known after apply)
    }

  # cloudstack_network_acl_rule.egress will be created
  + resource "cloudstack_network_acl_rule" "egress" {
      + acl_id      = (known after apply)
      + id          = (known after apply)
      + managed     = false
      + parallelism = 2

      + rule {
          + action       = "allow"
          + cidr_list    = [
              + "0.0.0.0/0",
            ]
          + icmp_code    = (known after apply)
          + icmp_type    = (known after apply)
          + ports        = []
          + protocol     = "all"
          + traffic_type = "egress"
          + uuids        = (known after apply)
        }
    }

  # cloudstack_network_acl_rule.ingress will be created
  + resource "cloudstack_network_acl_rule" "ingress" {
      + acl_id      = (known after apply)
      + id          = (known after apply)
      + managed     = false
      + parallelism = 2

      + rule {
          + action       = "allow"
          + cidr_list    = [
              + "0.0.0.0/0",
            ]
          + icmp_code    = (known after apply)
          + icmp_type    = (known after apply)
          + ports        = [
              + "443",
              + "80",
            ]
          + protocol     = "tcp"
          + traffic_type = "ingress"
          + uuids        = (known after apply)
        }
      + rule {
          + action       = "allow"
          + cidr_list    = [
              + "10.0.0.0/8",
            ]
          + icmp_code    = (known after apply)
          + icmp_type    = (known after apply)
          + ports        = [
              + "22",
            ]
          + protocol     = "tcp"
          + traffic_type = "ingress"
          + uuids        = (known after apply)
        }
    }

  # cloudstack_port_forward.ssh will be created
  + resource "cloudstack_port_forward" "ssh" {
      + id            = (known after apply)
      + ip_address_id = (known after apply)
      + managed       = false

      + forward {
          + private_port       = 22
          + protocol           = "tcp"
          + public_port        = 22
          + uuid               = (known after apply)
          + virtual_machine_id = (known after apply)
        }
    }

  # cloudstack_vpc.default will be created
  + resource "cloudstack_vpc" "default" {
      + cidr           = "192.168.0.0/16"
      + display_text   = "test-vpc"
      + id             = (known after apply)
      + name           = "test-vpc"
      + network_domain = (known after apply)
      + project        = (known after apply)
      + source_nat_ip  = (known after apply)
      + tags           = (known after apply)
      + vpc_offering   = "Default VPC offering"
      + zone           = "zone1"
    }

Plan: 8 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudstack_vpc.default: Creating...
cloudstack_vpc.default: Still creating... [10s elapsed]
cloudstack_vpc.default: Still creating... [20s elapsed]
cloudstack_vpc.default: Creation complete after 21s [id=9b549e57-898f-4bc0-a15d-2cbb6e9362b7]
cloudstack_network_acl.default: Creating...
cloudstack_network_acl.default: Creation complete after 1s [id=7baa7cad-fa9b-42ca-bf61-cac5a2510906]
cloudstack_network.testnet: Creating...
cloudstack_network_acl_rule.egress: Creating...
cloudstack_network_acl_rule.ingress: Creating...
cloudstack_network.testnet: Creation complete after 1s [id=5c220bee-f251-4039-8ae5-b1e10babb823]
cloudstack_instance.testvm: Creating...
cloudstack_ipaddress.public_ip: Creating...
cloudstack_ipaddress.public_ip: Creation complete after 1s [id=c1a607fa-8f3b-4264-b9db-e2654cc0430b]
cloudstack_network_acl_rule.egress: Creation complete after 2s [id=7baa7cad-fa9b-42ca-bf61-cac5a2510906]
cloudstack_network_acl_rule.ingress: Still creating... [10s elapsed]
cloudstack_instance.testvm: Still creating... [10s elapsed]
cloudstack_instance.testvm: Creation complete after 10s [id=a2551ce8-d7fc-4647-9b51-9d21a878f212]
cloudstack_port_forward.ssh: Creating...
cloudstack_port_forward.ssh: Creation complete after 4s [id=c1a607fa-8f3b-4264-b9db-e2654cc0430b]
cloudstack_network_acl_rule.ingress: Still creating... [20s elapsed]
cloudstack_network_acl_rule.ingress: Still creating... [30s elapsed]
cloudstack_network_acl_rule.ingress: Creation complete after 33s [id=7baa7cad-fa9b-42ca-bf61-cac5a2510906]

Apply complete! Resources: 8 added, 0 changed, 0 destroyed.

```
</details>

tfstate still has an empty value for `network_id`:
```
    {
      "mode": "managed",
      "type": "cloudstack_ipaddress",
      "name": "public_ip",
      "provider": "provider[\"registry.terraform.io/cloudstack/cloudstack\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "c1a607fa-8f3b-4264-b9db-e2654cc0430b",
            "ip_address": "10.44.121.9",
            "is_portable": false,
            "is_source_nat": false,
            "network_id": "",  <-- still empty
            "project": "",
            "tags": {},
            "vpc_id": "9b549e57-898f-4bc0-a15d-2cbb6e9362b7",
            "zone": "zone1"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "cloudstack_network.testnet",
            "cloudstack_network_acl.default",
            "cloudstack_vpc.default"
          ]
        }
      ]
    },

```

> So, I didn't change the default version of cloudstack-go imported in the resource_cloudstack_ipaddress.go file. If I follow the location of the cloudstack-go import, it takes me to [v2.11.0.](https://pkg.go.dev/github.com/apache/cloudstack-go/v2@v2.11.0/cloudstack)

I had to change the `go.mod` file so the cloudstack library uses a local copy I cloned. Basically, I appended these two lines to `go.mod`:
```
replace github.com/apache/cloudstack-go/v2 => ./cloudstack-go
exclude github.com/apache/cloudstack-go/v2 v2.11.0
```

Then re-run go build and copied the compiled terraform provider over the original binary.

**Comment by Damans227** [comment] 2022-05-01 18:16
Ok, I did some further testing, and it seems like when I define `network_id` and `vpc_id` together in an `ip_address` resource, the `network_id` ends up being stored as empty in the `.tfstate` file. I am not sure why that's the case, but I am looking into it.

**Comment by rcarson** [comment] 2022-08-24 22:41
Any update on this? Thanks!

**Comment by kiranchavala** [comment] 2024-03-05 15:16
@kohrar 

I am not hitting the issue on the latest build.

Let me know if i can close the issue 

<img width="1026" alt="Screenshot 2024-03-05 at 8 44 35 PM" src="https://github.com/apache/cloudstack-terraform-provider/assets/1401014/04e176a1-e77f-4081-9193-a798e79ccc66">

**Comment by kiranchavala** [comment] 2024-03-07 10:08
Closing the issue for now as its not observed on the latest build

**Comment by kohrar** [comment] 2024-03-08 22:21
Hi @kiranchavala. Thanks for picking up this project.

I gave this provider a try on Apache CloudStack 4.18.1 but seem to have some issues. I compiled the provider with the [most recent commits on the main branch](https://github.com/apache/cloudstack-terraform-provider/commit/e6079512a317cf2778f9bd6d5d08981df10c0ad6) at the time of this message and have the following results.

```
$ terraform -v
Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/cloudstack/cloudstack v0.4.1
```
0.4.1 is what I versioned the compiled plugin to avoid confusing it with the 0.4.0 release.


Here's what I defined in my project:
```
resource "cloudstack_ipaddress" "galaxy_public_ip" {
    vpc_id = "${cloudstack_vpc.default.id}"
    network_id = "${cloudstack_network.galaxy-net.id}"
    zone = "zone1"
    project = "${var.cloudstack_project_id}"
}
```

When I apply it, I see:

```
Terraform will perform the following actions:

  # cloudstack_ipaddress.galaxy_public_ip will be created
  + resource "cloudstack_ipaddress" "galaxy_public_ip" {
      + id            = (known after apply)
      + ip_address    = (known after apply)
      + is_portable   = false
      + is_source_nat = (known after apply)
      + network_id    = "5282446c-a837-48a2-9e77-d3add3cfc6df"
      + project       = "d037175d-b0bc-4aaa-801b-a1a7557b4b94"
      + tags          = (known after apply)
      + vpc_id        = "38652dce-c027-4a2c-b747-0a799ec97923"
      + zone          = "zone1"
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudstack_ipaddress.galaxy_public_ip: Creating...
cloudstack_ipaddress.galaxy_public_ip: Creation complete after 1s [id=85010dc9-87e9-4f52-9ba3-3e107ea37d70]

```

When I look at the terraform tfstate file, network_id is still missing:

```
    {
      "mode": "managed",
      "type": "cloudstack_ipaddress",
      "name": "galaxy_public_ip",
      "provider": "provider[\"registry.terraform.io/cloudstack/cloudstack\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "85010dc9-87e9-4f52-9ba3-3e107ea37d70",
            "ip_address": "10.44.122.76",
            "is_portable": false,
            "is_source_nat": false,
            "network_id": "",
            "project": "d037175d-b0bc-4aaa-801b-a1a7557b4b94",
            "tags": {},
            "vpc_id": "38652dce-c027-4a2c-b747-0a799ec97923",
            "zone": "zone1"
          },
```

**Comment by kohrar** [comment] 2024-03-08 22:29
> @kohrar
> 
> I am not hitting the issue on the latest build.
> 
> Let me know if i can close the issue
> 
> <img alt="Screenshot 2024-03-05 at 8 44 35 PM" width="1026" src="https://private-user-images.githubusercontent.com/1401014/310172823-04e176a1-e77f-4081-9193-a798e79ccc66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzM5OTYsIm5iZiI6MTcwOTkzMzY5NiwicGF0aCI6Ii8xNDAxMDE0LzMxMDE3MjgyMy0wNGUxNzZhMS1lNzdmLTQwODEtOTE5My1hNzk4ZTc5Y2NjNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMjEzNDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNjNDI2NWFhM2FlMDk0ZjVjZTJjNzlhMmViMGVmY2UwY2RlNTQyNjI1Zjk4N2QwYzY3MjdlMDBhZWE3NzllOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vbnPlbSBE35Y-226eMSMALHbShc4LOD9YOIdat8Dk_M">

I noticed also your vpc_id is empty. As mentioned by @Damans227 back in May 1, 2022, this bug seems to happen when both vpc_id and network_id are defined together.

**Comment by kiranchavala** [comment] 2024-03-11 02:39
Thanks @kohrar 

Able to reproduce the issue only when vpc_id and network_id are defined together.

Will look into it

**Comment by vishesh92** [comment] 2024-03-11 08:35
`associateIpAddress` command ignores the `networkid` if `vpcid` is set. That is why when both `vpc_id` & `network_id` are set in the terraform, `network_id` is not set in the state file.

Ref. code: https://github.com/apache/cloudstack/blob/6dc3d06037c39019f29686281856443c37a3e6c0/api/src/main/java/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java#L186-L189

**Comment by kiranchavala** [comment] 2024-03-11 10:31
Hi @kohrar 

Could you please let me know the reason you want the network id in the  terraform state file.

If you want to use the obtained network id in some pipeline, you can achieve it via 

1. terraform output

https://developer.hashicorp.com/terraform/language/values/outputs


```
output "networkid" {
value = cloudstack_ipaddress.galaxy_public_ip.network_id
}
```

2. Datasource

https://developer.hashicorp.com/terraform/language/data-sources

https://github.com/apache/cloudstack-terraform-provider/blob/main/cloudstack/data_source_cloudstack_ipaddress.go

**Closed** 2024-03-14 11:55 UTC

**Comment by kohrar** [comment] 2024-03-15 20:50
@vishesh92 I don't think that's a valid solution. There are cases where I need to specify both VPC and network ID. For instance, when I need to assign a public IP address to a specific network within a specific VPC.

Not specifying both results in an error. Here's an example:

```
│ Error: Error associating a new IP address: Undefined error: {"errorcode":431,"errortext":"Can't assign ip to the network directly when network belongs to VPC.Specify vpcId to associate ip address to VPC"}
│
│   with cloudstack_ipaddress.test_public_ip,
│   on guacamole.tf line 151, in resource "cloudstack_ipaddress" "test_public_ip":
│  151: resource "cloudstack_ipaddress" "test_public_ip" {
│
```

This is what I'm using:

```
resource "cloudstack_ipaddress" "test_public_ip" {
    # vpc_id = "${cloudstack_vpc.default.id}"
    network_id = "${cloudstack_network.guacamole-net.id}"
    zone = "zone1"

    project = "${var.cloudstack_project_id}"
}
```

**Comment by kohrar** [comment] 2024-03-15 21:00
Perhaps I'm misunderstanding how public IPs are assigned to VPC and networks. I don't actually need to specify the network if I'm using VPCs.

The above example would work if I specified the VPC only as the network_id isn't necessary.

**Comment by vishesh92** [comment] 2024-06-06 15:58
@kohrar You don't need to specify network id if you are specifying VPC. Public IPs get assigned to the VPC itself, which is the parent of its network tiers.
