### ISSUE TITLE
Using datasource cloudstack_template crashes the provider

### ISSUE THREAD

**Issue by codemoos** [apache/cloudstack-terraform-provider#46] opened 2023-01-05 12:50 UTC
Plugin crashes when passing name = display_text in datasource cloudstack_template, as shown below code block.
```
data "cloudstack_template" "my_template" {
  template_filter = "featured"

  filter {
    name = "display_text"
    value = "Ubuntu 22.04"
  }
}
```

What does work is passing name = name with value = "Ubuntu"

```
data "cloudstack_template" "my_template" {
  template_filter = "featured"

  filter {
    name = "name"
    value = "Ubuntu 22.04"
  }
}
```

### Response 
Error: Plugin did not respond
│ 
│   with data.cloudstack_template.my_template,
│   on firstdeployment.tf line 36, in data "cloudstack_template" "my_template":
│   36: data "cloudstack_template" "my_template" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudstack_v0.4.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 23 [running]:
github.com/terraform-providers/terraform-provider-cloudstack/cloudstack.applyFilters(0xc0001983e0, 0x1c28e53)
        github.com/terraform-providers/terraform-provider-cloudstack/cloudstack/data_source_cloudstack_template.go:184 +0x292
github.com/terraform-providers/terraform-provider-cloudstack/cloudstack.dataSourceCloudstackTemplateRead(0xc000528270, {0x1af41a0, 0xc0000dcb00})
        github.com/terraform-providers/terraform-provider-cloudstack/cloudstack/data_source_cloudstack_template.go:106 +0x2cd
github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc000292a80, 0x1a9e980, {0x1af41a0, 0xc0000dcb00})
        github.com/hashicorp/terraform@v0.12.0/helper/schema/resource.go:390 +0x66
github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000293a00, 0xc000177988, 0x1a9e980)
        github.com/hashicorp/terraform@v0.12.0/helper/schema/provider.go:442 +0x65
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e518, {0xc000190dc0, 0x10aede6}, 0xc000190dc0)
        github.com/hashicorp/terraform@v0.12.0/helper/plugin/grpc_provider.go:990 +0x2e5
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1badca0, 0xc00000e518}, {0x1da4170, 0xc00015acc0}, 0xc00057d2c0, 0x0)
        github.com/hashicorp/terraform@v0.12.0/internal/tfplugin5/tfplugin5.pb.go:3055 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00045a600, {0x1db1338, 0xc00045a780}, 0xc000539b00, 0xc000546420, 0x24107b0, 0x0)
        google.golang.org/grpc@v1.18.0/server.go:966 +0xe47
google.golang.org/grpc.(*Server).handleStream(0xc00045a600, {0x1db1338, 0xc00045a780}, 0xc000539b00, 0x0)
        google.golang.org/grpc@v1.18.0/server.go:1245 +0x9e5
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.18.0/server.go:685 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.18.0/server.go:683 +0xef

Error: The terraform-provider-cloudstack_v0.4.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by Damans227** [comment] 2023-01-05 14:50
Seems like a duplicate of https://github.com/apache/cloudstack-terraform-provider/issues/42. I also provided a fix for this issue which is merged already https://github.com/apache/cloudstack-terraform-provider/pull/43. Are you on the latest build @codemoos ?

**Comment by codemoos** [comment] 2023-01-05 15:24
Aah thanks, did not see that one. But the latest release is from feb 2022, this fix is merged after.

**Comment by Damans227** [comment] 2023-01-05 15:47
I see. Can you do a quick test, and use following as a filter: 

```
  filter {
    name = "displaytext"
    value = "Ubuntu 22.04"
  }
}
```

If that works, then you can use it as a workaround for now. The fix shall become available in the next release.

**Comment by codemoos** [comment] 2023-01-05 17:44
Yes, that works!

**Closed** 2023-01-05 17:45 UTC
