### ISSUE TITLE
API backward compatibility problem while deploying virtual machines using human readable template reference name

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-terraform-provider#18] opened 2021-11-28 04:22 UTC
# Problem description
On creating a VM with API 4.11, the following error message appears.

```
Error retrieving ID of template debian 11 bullseye BUILD-459629: json: 
cannot unmarshal object into Go struct field 
ListTemplatesResponse.template of type []interface {}
```
This issue was in discussion [here](https://github.com/xanzy/terraform-provider-cloudstack/issues/72).
So it's a problem with the underlying SDK as reported in its [repo](https://github.com/apache/cloudstack-go/issues/15).

# Synopsis

## Backend details

Check the field child template with ```list templates``` with Cloud Monkey:

```
|  ID          | CHILDTEMPLATES |              NAME              |        ZONENAME     |  
+--------------------------------------+----------------+--------------------------------+-----------
| ffe4c50b-... | {}             | ubuntu 20.04 focal             | Advanced zone           | 
| ffe4c50b-... | {}             | ubuntu 20.04 focal             | Basic zone           | 
```

So it seems that this field has different setting depending on the zone.

## Output with loglevel set as TFLOG=TRACE 
It seems like while providing the human readable name of the template resource, the provider can't manage properly its ID's lookup.
```
021-11-28T11:59:57.313Z [DEBUG] provider.terraform-provider-cloudstack_v0.4.0-rc1: 2021/11/28 11:59:57 [DEBUG] Retrieving ID of template: debian 11 bullseye BUILD-459629
2021-11-28T11:59:57.786Z [TRACE] maybeTainted: module.bastion_runner.cloudstack_instance.bastionrunner encountered an error during creation, so it is now marked as tainted
```

# Workaround
* Use hardcoded template ID (UUID) instead of human readable name
* Error does not appear, VM deploys.

**Comment by harikrishna-patnala** [comment] 2021-11-29 12:00
@synergiator I checked the other ticket on cloudstack-go and you are saying it is not reproducible now. Is it still a problem deploying a VM using terraform ? I know there used to be a problem with ACS 4.10 version because child template is not there in that version, but are you still facing the same problem with ACS 4.11 ?

**Comment by synergiator** [comment] 2021-11-29 13:20
This data is from API 4.11 (a patched fork of it though); with the terraform provider I can reproduce this. Will run another unit test for cloudstack-go to confirm there. I'd like to run the test against native 4.11 but have currently no (fast) such  possibility.

**Comment by synergiator** [comment] 2021-12-27 14:41
depends on https://github.com/apache/cloudstack-go/issues/15?

**Comment by kiranchavala** [comment] 2024-03-05 16:24
@synergiator 

Not able to reproduce the issue able to deploy instance by giving the template name, tested on the latest cloudstack 4.19 release.

Let me know if i can go ahead and close the issue 

 ```
 # cloudstack_instance.test-vm will be created
  + resource "cloudstack_instance" "test-vm" {
      + display_name     = (known after apply)
      + expunge          = true
      + group            = (known after apply)
      + id               = (known after apply)
      + ip_address       = (known after apply)
      + name             = "hyd-demo-test"
      + network_id       = (known after apply)
      + project          = (known after apply)
      + root_disk_size   = (known after apply)
      + service_offering = "9c870dca-a857-468c-a804-29b256af6b53"
      + start_vm         = true
      + tags             = (known after apply)
      + template         = "Centos7"
      + zone             = "49e9ad34-8a3d-4f87-8ff5-90d65859f839"
    }
    
```

**Comment by kiranchavala** [comment] 2024-03-07 10:13
Closing the issue as it not reproducible on the latest build and also mentioned cloudstack version 4.11  is too old

**Closed by kiranchavala** 2024-03-07 10:13 UTC
